### PR TITLE
Update allowlist.ts

### PR DESCRIPTION
**Pull request by hunterparks**

### CODE REVIEW

**Review by drillskibo — COMMENTED** [review]
Who are you on Twitch ? 🤔

**Comment by hunterparks** [comment]
I am 🙂

**Comment by drillskibo** [comment]
Only VIPs and mods can be on this allowlist.
If you are not confirmed to be one of them, this PR will not be merged.

**Comment by hunterparks** [comment]
Per CJ's instructions on stream, I sent him on Discord with my Twitch-linked account.

**Comment by drillskibo** [comment]
Following internal investigation, it results you are currently not a moderator nor a VIP of the Twitch channel.
This PR can then be closed.
Please wait to maybe become one or the other in the future, to subsequently open a new PR for this matter.
Thank you for your understanding.

**Comment by hunterparks** [comment]
Sounds good @drillskibo. Sorry for the bother - @w3cj told me on steam than he’d add me if I DM’d him in Discord and submitted the PR, but I understand and will remove the request. Thanks!

**Comment by drillskibo** [comment]
Became a VIP yesterday ! This PR can then be reopened.

**Pull request merged**
